export default {
  monthSearch: (state) => state.monthSearch,
  selectedTimeRange: (state) => state.selectedTimeRange,
  salaryListHeader: (state) => state.salaryListHeader,
  salaryList: (state) => state.salaryList,
  totalPage: (state) => state.totalPage,
  salaryDetail: (state) => state.salaryDetail,
  salaryDataList: (state) => state.salaryDataList,
  listSalaryId: (state) => state.listSalaryId,
  editDeductionDialogVisible: (state) => state.editDeductionDialogVisible,
  yearSearch: (state) => state.yearSearch,
  salaryHistoryListHeader: (state) => state.salaryHistoryListHeader,
  salaryHistoryDataList: (state) => state.salaryHistoryDataList,
  editAdvanceDialogVisible: (state) => state.editAdvanceDialogVisible,
  editBonusDialogVisible: (state) => state.editBonusDialogVisible,
  salaryHistoryList: (state) => state.salaryHistoryList,
}
