export default {
  selectedTimeRange: (state) => state.selectedTimeRange,
  listEmployeeTimekeeping: (state) => state.listEmployeeTimekeeping,
  timekeepingInDay: (state) => state.timekeepingInDay,
  allTimeKeeping: (state) => state.allTimeKeeping,
  listEmployeeId: (state) => state.listEmployeeId,
  listOfficeFilter: (state) => state.listOfficeFilter,
  listAreaFilter: (state) => state.listAreaFilter,
  totalPage: (state) => state.totalPage,
  workingDataList: (state) => state.workingDataList,
  monthSearch: (state) => state.monthSearch,
  columns: (state) => state.columns,
  isCheckIn: (state) => state.isCheckIn,
  selectedEmployeeName: (state) => state.selectedEmployeeName,
}
