export default {
  personnelList: (state) => state.personnelList,
  personnelDetail: (state) => state.personnelDetail,
  columns: (state) => state.columns,
  workingStatus: (state) => state.workingStatus,
  genderList: (state) => state.genderList,
  roles: (state) => state.roles,
  centerDialogVisible: (state) => state.centerDialogVisible,
  workingTypes: (state) => state.workingTypes,
  listGrade: (state) => state.listGrade,
  listOffice: (state) => state.listOffice,
  listArea: (state) => state.listArea,
  employeeTypes: (state) => state.employeeTypes,
  taxList: (state) => state.taxList,
  bankInfo: (state) => state.bankInfo,
  additionInfo: (state) => state.additionInfo,
  workingHistory: (state) => state.workingHistory,
  relativeInfo: (state) => state.relativeInfo,
  educationInfo: (state) => state.educationInfo,
  listPositions: (state) => state.listPositions,
  isEditTaxInfo: (state) => state.isEditTaxInfo,
  isEditBankInfo: (state) => state.isEditBankInfo,
  isEditLine: (state) => state.isEditLine,
  isEditLineRelative: (state) => state.isEditLineRelative,
  isEditLineEducation: (state) => state.isEditLineEducation,
  isEditMainInfo: (state) => state.isEditMainInfo,
}
